[package]
name = "aoc"
version = "0.1.0"
authors = ["drin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "day04"
src = "src/bin/day04.rs"
